"""update title

Revision ID: 19a169ae82f4
Revises: 80e7ca95d05
Create Date: 2015-10-06 16:16:40.994770

"""

# revision identifiers, used by Alembic.
revision = '19a169ae82f4'
down_revision = '80e7ca95d05'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
