"""9090

Revision ID: 3792287497fa
Revises: 38c93b1b80c4
Create Date: 2015-12-04 17:11:25.058404

"""

# revision identifiers, used by Alembic.
revision = '3792287497fa'
down_revision = '38c93b1b80c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
